apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        envFrom:
          - configMapRef:
              name: nginx-configmap
              optional: false
          - secretRef:
              name: nginx-secret
              optional: false
        ports:
        - containerPort: 80
