---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        envFrom:
          - configMapRef:
              name: nginx-configmap
              optional: false
          - secretRef:
              name: nginx-secret
              optional: false
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx-proxy
  labels:
    app: nginx
    env: dev
data:
  APP_ENV: "dev"
  APP_NAME: "webserver"
  APP_TYPE: "proxy"


---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: nginx-proxy
type: Opaque
data:
  SECURITY_TOKEN: d29yZHByZXNzCg==            ## base64 encoded value of original password. Use command: echo -n wordpress | base64
  PASSWORD: d3AxMjM0NQ==

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80      # mush be matched with container port in the pod
