## While base64 encoding, use -n option to discard the trailing newline

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: nginx-proxy
type: Opaque
data:
  SECURITY_TOKEN: d29yZHByZXNzCg==            ## base64 encoded value of original password. Use command: echo -n wordpress | base64
  PASSWORD: d3AxMjM0NQ==
