---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        #ports:
        #- containerPort: 80
