db:
    secrets:
        MYSQL_PASSWORD: ENC[AES256_GCM,data:z9lBpa4VQjmI,iv:wUCYKOFu57qxAl9rE/TGjYTwRgbIAszk37UK7fxFwBU=,tag:vPoAaxQQNFjqX32I9xMfDw==,type:str]
        MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:67+OXv6mYDeI,iv:8RRz2IYifFnFMZaigbX2eQCF1IvluL9Po2of+fgCVxE=,tag:EpyTOM/2NXPnfS0sFYMADg==,type:str]
        MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:0TNY5raoBkYN,iv:tvLw/kebzlwMmaOdd2kt6M6XEsm2TVfGgJE/GcoJrBM=,tag:ArUIM99TgTLlSBpqTBAJrw==,type:str]
        FOO: ENC[AES256_GCM,data:s87n,iv:dHO3LI3jxCEiJisqRC+0pZJ2ceKSp+SqSir5b+/cgQc=,tag:XAFulfEyxsRK1wOhRX9Fbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1taju3pspwqtuqfk3p4glfytjflazlx00a6yue3f72vfnkcfzva6s75whf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeVRESDBUTVNqYitsK29Q
            eTdBZk5uSExBZDN6S2RKNkRQU3d0cGpmcXdVCmlFTEFsM3VLZk02UUtsNGRRVHhC
            MU5DKzByd21uQ0trZm9lL2FUVHIzUE0KLS0tIFpPOGdNcWRCNFJNWlUzdUZDbGRi
            c1o1Y3ZEd1AzMmhxcGdzbU9Zb3ZZdEkKwLXTpK/mGshymyAnVIwCjqkCoRmNzuCp
            k7WfbSNNYX3phyynoGibM0JssM+PIuBCEABNqVIwWs6YG9UeG8t+9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T13:50:02Z"
    mac: ENC[AES256_GCM,data:9Kd175GDb0bVXofHkyEJmn9i44YmdTeR9ndkqIjk7NJ+htOmkGPPTnbjXbFGDIi25/lpKO05S2cVea8BeYrKUztTOx5P0QYXRvDIQu9Del25dfxbJyGABORFpMSTe7xefuVOxLSM76GN+YgXzxILZSmQ8ME7VqStzgYHWrHtnLA=,iv:vhRj5ajOgEp/Jxpg65FBsWFgP5oOAMWGqEsRkCTq75o=,tag:od9skLpgFLQufnceQcxVaA==,type:str]
    pgp: []
    encrypted_regex: ^(secrets)$
    version: 3.8.1
