#Ceate Namespace named wp
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wpapp
  name: wp-app-configmap
  labels:
    app: wp-app
    env: dev
    stack: wordpress
data:
  APP_ENV: "dev"
  WORDPRESS_DB_HOST: "wp-database-service.wpdb.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: wpapp
  name: wp-app-secret
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: "d29yZHByZXNzCg=="       ## base64 decoded value of original password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wpapp
  name: wp-app-deployment
  labels:
    app: wp-app
    env: dev
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: wp-app
      env: dev
      stack: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-app
        env: dev
        stack: wordpress
    spec:
      containers:
      - name: wp-app
        image: msalim22/wp:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: wp-app-configmap
              optional: false
          - secretRef:
              name: wp-app-secret
              optional: false
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: wpapp
  name: wp-app-service
  labels:
    app: wp-app
    env: dev
    stack: wordpress
spec:
  type: NodePort
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 80       # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    app: wp-app
    env: dev
    stack: wordpress       # Pod label that service is using to select Pods
