---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-app-configmap
  labels:
    app: wp-app
    env: dev
    stack: wordpress
data:
  APP_ENV: "dev"
  WORDPRESS_DB_HOST: "wp-database-service.wpdb.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"
