---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app-deployment
  labels:
    app: wp-app
    env: dev
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: wp-app
      env: dev
      stack: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-app
        env: dev
        stack: wordpress
    spec:
      containers:
      - name: wp-app
        image: msalim22/wp:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: wp-app-configmap
              optional: false
          - secretRef:
              name: wp-app-secret
              optional: false
        ports:
        - containerPort: 80
