---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-database-configmap
  labels:
    app: db
    env: dev
    stack: wordpress
data:
  APP_ENV: "dev"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
